### ISSUE TITLE
Closing notification and leaving the box stops closing

### ISSUE THREAD

**Issue by dzek69** [sciactive/pnotify#166]
To see this effect simply go to: 
http://sciactive.com/pnotify/#demos-simple
Activate regular notice, hover on it, click close, and when it ends its fading - move cursor out of notification - it will fade in again.

**Comment by danielzabotti** [comment]
I'v got the same issue. Turns out it was already addressed here https://github.com/sciactive/pnotify/commit/20533ef15eb10aa9a70163ccb517629025ef6691#diff-67eaf0b2833e394723b5740551b725bf

The problem is with the custom javascript builder using old cached versions of files.

**Comment by Nickproger** [comment]
@danielzabotti
The same issue. When it going to be fixed?

**Comment by neooleg** [comment]
@danielzabotti thanks a lot for referencing the commit. However, looks like the problem isn't in JavaScript builder. I've downloaded from GitHub the actual release (2.0.1), but this fix is absent there. So the issue still reproduces.

Probably it's a regress or perhaps the fix has some side effects that's why it was removed knowingly.

**Comment by smajl** [comment]
I guess builder has to be using some old cached files, because demo/docs site is currently free of this bug and is referencing the new AMD files separately.

When you do custom build, you get old code.

**Comment by andreacimbalo** [comment]
Bug still present on 30th June 2015.

**Comment by knguyen6** [comment]
Apparently, the bug is present in the main stable site http://sciactive.com/pnotify/#demos-simple, 
and I think it's fixed for the demo on development site http://sciactive.github.io/pnotify/#demos-simple
